#!/usr/bin/env python3
"""Record and summarize reviewed manual release acceptance evidence."""

from __future__ import annotations

import argparse
from dataclasses import asdict, dataclass, replace
from datetime import datetime, timezone
import json
import os
from pathlib import Path
import re
import sys
from typing import Any

from memorylib import FrontmatterError, is_date_string, parse_frontmatter_text, repo_relative_path, repo_root, slugify
from secret_scan import scan_text


ACCEPTANCE_ITEMS: dict[str, str] = {
    "obsidian-vault": "Export the generated vault template and inspect Obsidian-compatible templates; open it in Obsidian when a GUI reviewer is available.",
    "mcp-client-installed": "Use one real MCP client with installed CLI config.",
    "mcp-client-docker": "Use one real MCP client with Docker config if Docker is supported.",
    "proposal-capture": "Capture one non-secret proposal and review its inbox file.",
    "provider-import": "Import one non-secret provider fixture and review its inbox file.",
    "git-lesson": "Capture one git lesson candidate and review its inbox file.",
    "daily-maintenance": "Run one daily maintenance pass and inspect index, graph, weights, and report artifacts.",
    "review-reports": "Generate false-positive and conflict reports, then review one intentional case or the empty-report evidence.",
    "testpypi-publish": (
        "Publish to TestPyPI only after package and Docker smoke pass in CI and publish workflow preflight."
    ),
}

SUGGESTED_ACCEPTANCE_ARTIFACTS: dict[str, list[str]] = {
    "obsidian-vault": [
        "generated vault export path or command output",
        "path to inspected Obsidian-compatible template file(s)",
    ],
    "mcp-client-installed": [
        "MCP client config generated by `ai-dememory mcp-config --client <client>`",
        "client log or PR comment showing initialize and ping with installed CLI",
    ],
    "mcp-client-docker": [
        "Docker MCP client config generated with `--mode docker`",
        "client log or PR comment showing initialize and ping through the local image",
    ],
    "proposal-capture": [
        "reviewed inbox proposal path under `inbox/`",
        "summary of why the captured proposal was non-secret",
    ],
    "provider-import": [
        "reviewed provider import inbox path",
        "sanitized fixture name or source reference used for import",
    ],
    "git-lesson": [
        "reviewed git lesson inbox path",
        "commit range or repository path used for lesson capture",
    ],
    "daily-maintenance": [
        "`reports/maintenance/` report path",
        "`indexes/memory.sqlite`, `indexes/memory-graph.json`, `indexes/memory-weights.json`, and lifecycle artifact paths",
    ],
    "review-reports": [
        "`reports/false-positives.md`",
        "`reports/conflicts.md`",
        "review notes for one intentional finding, conflict, or empty-report state",
    ],
    "testpypi-publish": [
        "TestPyPI Trusted Publishing workflow URL",
        "publish workflow preflight log showing install, package build, and Docker smoke",
        "fresh TestPyPI install smoke log",
    ],
}

STATUSES = {"passed", "blocked"}
DEFAULT_ACCEPTANCE_PLAN_REPORT = Path("reports/manual-acceptance-plan.md")
DEFAULT_ACCEPTANCE_PACKET_REPORT = Path("reports/manual-acceptance-packet.md")
DEFAULT_ACCEPTANCE_PACKET_ARCHIVE_DIR = Path("reports/manual-acceptance-packets")


@dataclass(frozen=True)
class AcceptanceRecord:
    path: str
    item: str
    status: str
    reviewed_by: str
    reviewed_at: str
    summary: str
    artifacts: list[str]


@dataclass(frozen=True)
class AcceptanceItemStatus:
    id: str
    description: str
    completed: bool
    records: list[AcceptanceRecord]


@dataclass(frozen=True)
class AcceptanceVerification:
    complete: bool
    total: int
    completed: list[dict[str, Any]]
    blocked: list[dict[str, Any]]
    remaining: list[dict[str, Any]]


@dataclass(frozen=True)
class AcceptancePlanItem:
    id: str
    description: str
    status: str
    completed: bool
    record_count: int
    latest_record: dict[str, Any] | None
    suggested_artifacts: list[str]
    pass_command: str | None
    blocked_command: str | None
    next_action: str


@dataclass(frozen=True)
class AcceptancePlan:
    complete: bool
    total: int
    completed_count: int
    blocked_count: int
    remaining_count: int
    items: list[AcceptancePlanItem]
    next_actions: list[str]
    limit: int | None = None
    offset: int = 0
    returned_count: int = 0
    next_offset: int | None = None
    has_more: bool = False
    reviewer: str | None = None
    pr_url: str | None = None


@dataclass(frozen=True)
class AcceptanceTemplate:
    item: str
    description: str
    status: str
    reviewer: str | None
    pr_url: str | None
    suggested_artifacts: list[str]
    command: str
    markdown: str
    mutates_system: bool
    writes_files: bool
    records_evidence: bool


@dataclass(frozen=True)
class AcceptancePacketArchiveEntry:
    path: str
    size_bytes: int
    modified_at: str
    generated_at: str | None


def acceptance_dir(root: Path) -> Path:
    return root / "inbox" / "release-acceptance"


def safe_acceptance_dir(root: Path, *, create: bool) -> Path | None:
    root_abs = root.resolve()
    inbox = root_abs / "inbox"
    directory = inbox / "release-acceptance"
    for component in (inbox, directory):
        if component.is_symlink():
            raise ValueError("acceptance evidence path must not contain symlinks")
        if component.exists():
            try:
                component.resolve().relative_to(root_abs)
            except ValueError as exc:
                raise ValueError("acceptance evidence path must stay inside the memory root") from exc
    if not create and not directory.exists():
        return None
    if create:
        directory.mkdir(parents=True, exist_ok=True)
    for component in (inbox, directory):
        if component.is_symlink():
            raise ValueError("acceptance evidence path must not contain symlinks")
        if component.exists():
            try:
                component.resolve().relative_to(root_abs)
            except ValueError as exc:
                raise ValueError("acceptance evidence path must stay inside the memory root") from exc
    return directory


def frontmatter_scalar(value: str) -> str:
    clean = " ".join(str(value).splitlines()).strip().replace('"', "'")
    return json.dumps(clean)


def frontmatter_list(values: list[str]) -> str:
    return "[" + ", ".join(frontmatter_scalar(value) for value in values) + "]"


def validate_item(item: str) -> None:
    if item not in ACCEPTANCE_ITEMS:
        raise ValueError("unknown acceptance item; use `ai-dememory acceptance list`")


def record_acceptance(
    root: Path,
    item: str,
    status: str,
    reviewed_by: str,
    summary: str,
    artifacts: list[str] | None = None,
) -> Path:
    validate_item(item)
    if status not in STATUSES:
        raise ValueError("status must be passed or blocked")
    reviewed_by = reviewed_by.strip()
    summary = summary.strip()
    artifacts = [artifact.strip() for artifact in (artifacts or []) if artifact.strip()]
    if not reviewed_by:
        raise ValueError("reviewed_by is required")
    if not summary:
        raise ValueError("summary is required")

    scan_target = "\n".join([item, status, reviewed_by, summary, *artifacts])
    if scan_text(scan_target, "<manual-acceptance>"):
        raise ValueError("acceptance evidence rejected by secret scan")

    now = datetime.now(timezone.utc).replace(microsecond=0)
    directory = safe_acceptance_dir(root, create=True)
    assert directory is not None
    stem = f"{now.strftime('%Y%m%dT%H%M%SZ')}_{slugify(item, 'acceptance')}"
    path = directory / f"{stem}.md"
    suffix = 1
    while path.exists() or path.is_symlink():
        path = directory / f"{stem}_{suffix}.md"
        suffix += 1
    artifact_lines = "\n".join(f"- {artifact}" for artifact in artifacts) if artifacts else "- none"
    text = f"""---
type: manual-acceptance
status: {status}
acceptance_item: {frontmatter_scalar(item)}
reviewed_by: {frontmatter_scalar(reviewed_by)}
reviewed_at: {now.date().isoformat()}
summary: {frontmatter_scalar(summary)}
artifacts: {frontmatter_list(artifacts)}
---

# Manual Acceptance: {item}

{ACCEPTANCE_ITEMS[item]}

## Summary

{summary}

## Artifacts

{artifact_lines}
"""
    if scan_text(text, "<manual-acceptance.rendered>"):
        raise ValueError("acceptance evidence rejected by rendered secret scan")
    path.write_text(text, encoding="utf-8")
    return path


def load_acceptance_records(root: Path) -> list[AcceptanceRecord]:
    try:
        directory = safe_acceptance_dir(root, create=False)
    except ValueError:
        return []
    if directory is None:
        return []
    records: list[AcceptanceRecord] = []
    for path in sorted(directory.glob("*.md")):
        if path.is_symlink():
            continue
        try:
            path.resolve().relative_to(directory.resolve())
        except ValueError:
            continue
        try:
            frontmatter, _ = parse_frontmatter_text(path.read_text(encoding="utf-8"), path)
        except (OSError, FrontmatterError):
            continue
        record = record_from_frontmatter(root, path, frontmatter)
        if record:
            records.append(record)
    return records


def record_from_frontmatter(root: Path, path: Path, data: dict[str, Any]) -> AcceptanceRecord | None:
    if data.get("type") != "manual-acceptance":
        return None
    item = data.get("acceptance_item")
    status = data.get("status")
    reviewed_by = data.get("reviewed_by")
    reviewed_at = data.get("reviewed_at")
    summary = data.get("summary")
    artifacts = data.get("artifacts", [])
    if item not in ACCEPTANCE_ITEMS or status not in STATUSES:
        return None
    if not isinstance(reviewed_by, str) or not reviewed_by.strip():
        return None
    if not is_date_string(reviewed_at):
        return None
    if not isinstance(summary, str) or not summary.strip():
        return None
    if not isinstance(artifacts, list) or not all(isinstance(artifact, str) for artifact in artifacts):
        artifacts = []
    return AcceptanceRecord(
        path=repo_relative_path(path, root),
        item=str(item),
        status=str(status),
        reviewed_by=reviewed_by,
        reviewed_at=str(reviewed_at),
        summary=summary,
        artifacts=list(artifacts),
    )


def acceptance_status(root: Path) -> list[AcceptanceItemStatus]:
    records = load_acceptance_records(root)
    by_item: dict[str, list[AcceptanceRecord]] = {item: [] for item in ACCEPTANCE_ITEMS}
    for record in records:
        by_item.setdefault(record.item, []).append(record)
    return [
        AcceptanceItemStatus(
            id=item,
            description=description,
            completed=bool(by_item.get(item)) and by_item.get(item, [])[-1].status == "passed",
            records=by_item.get(item, []),
        )
        for item, description in ACCEPTANCE_ITEMS.items()
    ]


def remaining_acceptance_items(root: Path) -> list[str]:
    return [item.description for item in acceptance_status(root) if not item.completed]


def verify_acceptance(items: list[AcceptanceItemStatus]) -> AcceptanceVerification:
    completed: list[dict[str, Any]] = []
    blocked: list[dict[str, Any]] = []
    remaining: list[dict[str, Any]] = []
    for item in items:
        row = {
            "id": item.id,
            "description": item.description,
            "records": [asdict(record) for record in item.records],
        }
        if item.completed:
            completed.append(row)
        else:
            remaining.append(row)
            if any(record.status == "blocked" for record in item.records):
                blocked.append(row)
    return AcceptanceVerification(
        complete=not remaining,
        total=len(items),
        completed=completed,
        blocked=blocked,
        remaining=remaining,
    )


def command_arg(value: str) -> str:
    normalized = " ".join(str(value).splitlines()).strip()
    return "'" + normalized.replace("'", "'\"'\"'") + "'"


def markdown_code_span(value: str | None, default: str = "not provided") -> str:
    text = value if isinstance(value, str) and value else default
    text = re.sub(r"\s+", " ", text).strip() or default
    max_backtick_run = max((len(match.group(0)) for match in re.finditer(r"`+", text)), default=0)
    delimiter = "`" * (max_backtick_run + 1)
    if text.startswith("`") or text.endswith("`"):
        text = f" {text} "
    return f"{delimiter}{text}{delimiter}"


def acceptance_record_command(
    item_id: str,
    status: str = "passed",
    *,
    reviewer: str | None = None,
    pr_url: str | None = None,
) -> str:
    reviewed_by = reviewer.strip() if isinstance(reviewer, str) and reviewer.strip() else "Reviewer Name"
    artifacts = [pr_url.strip()] if isinstance(pr_url, str) and pr_url.strip() else ["<path-or-url>"]
    pieces = [
        "ai-dememory acceptance record",
        f"--item {item_id}",
        f"--reviewed-by {command_arg(reviewed_by)}",
        "--summary 'Reviewed evidence summary.'",
    ]
    if status != "passed":
        pieces.insert(2, f"--status {status}")
    for artifact in artifacts:
        pieces.append(f"--artifact {command_arg(artifact)}")
    return " ".join(pieces)


def resolve_repo_path(root: Path, path: str | Path) -> Path:
    candidate = Path(path)
    if not candidate.is_absolute():
        candidate = root / candidate
    return candidate.resolve()


def render_acceptance_plan_report(plan: AcceptancePlan) -> str:
    lines = [
        "# Manual Acceptance Plan",
        "",
        "This generated report plans manual release acceptance work. It does not",
        "record evidence, complete acceptance, publish packages, or replace human",
        "review.",
        "",
        "## Summary",
        "",
        f"- complete: `{str(plan.complete).lower()}`",
        f"- completed: `{plan.completed_count}/{plan.total}`",
        f"- remaining_count: `{plan.remaining_count}`",
        f"- blocked_count: `{plan.blocked_count}`",
        f"- reviewer: {markdown_code_span(plan.reviewer)}",
        f"- pr_url: {markdown_code_span(plan.pr_url)}",
        "",
    ]

    for section_status, title in [
        ("remaining", "Remaining"),
        ("blocked", "Blocked"),
        ("passed", "Completed"),
    ]:
        section_items = [item for item in plan.items if item.status == section_status]
        lines.extend([f"## {title}", ""])
        if not section_items:
            lines.extend([f"_No {title.lower()} manual acceptance items._", ""])
            continue
        for item in section_items:
            lines.extend(
                [
                    f"### {item.id}",
                    "",
                    f"- status: `{item.status}`",
                    f"- completed: `{str(item.completed).lower()}`",
                    f"- record_count: `{item.record_count}`",
                    f"- description: {item.description}",
                    f"- next_action: {item.next_action}",
                    "",
                    "Suggested Artifacts:",
                    "",
                ]
            )
            lines.extend(f"- {artifact}" for artifact in item.suggested_artifacts)
            lines.append("")
            if item.latest_record:
                latest = item.latest_record
                lines.extend(
                    [
                        "Latest Record:",
                        "",
                        f"- path: `{latest.get('path')}`",
                        f"- status: `{latest.get('status')}`",
                        f"- reviewed_by: `{latest.get('reviewed_by')}`",
                        f"- reviewed_at: `{latest.get('reviewed_at')}`",
                        f"- summary: {latest.get('summary')}",
                        "",
                    ]
                )
            else:
                lines.extend(["Latest Record:", "", "_No reviewed records._", ""])
            if item.pass_command or item.blocked_command:
                lines.extend(["Record Commands:", ""])
                if item.pass_command:
                    lines.extend(["Pass:", "", "```bash", item.pass_command, "```", ""])
                if item.blocked_command:
                    lines.extend(["Block:", "", "```bash", item.blocked_command, "```", ""])

    lines.extend(["## Next Actions", ""])
    lines.extend(f"- {action}" for action in plan.next_actions)
    lines.extend(
        [
            "",
            "## Boundaries",
            "",
            "- This is a generated planning artifact under `reports/`.",
            "- It does not record evidence or count as manual acceptance.",
            "- Run `ai-dememory acceptance record` only after a reviewer has real proof.",
            "- Run `ai-dememory acceptance verify` and `ai-dememory release-evidence --strict` before release.",
            "",
        ]
    )
    return "\n".join(lines)


def write_acceptance_plan_report(
    root: Path,
    plan: AcceptancePlan,
    report_path: str | Path = DEFAULT_ACCEPTANCE_PLAN_REPORT,
) -> Path:
    target = resolve_acceptance_generated_report_path(root, report_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    text = render_acceptance_plan_report(plan)
    if scan_text(text, "<manual-acceptance-plan-report>"):
        raise ValueError("acceptance plan report rejected by secret scan")
    target.write_text(text, encoding="utf-8")
    return target


def render_acceptance_packet_report(plan: AcceptancePlan) -> str:
    lines = [
        "# Manual Acceptance Packet",
        "",
        "This generated packet gives reviewers one fill-in artifact for manual",
        "v2 release acceptance. It does not record evidence, complete",
        "acceptance, publish packages, or replace human review.",
        "",
        "## Packet Summary",
        "",
        f"- complete: `{str(plan.complete).lower()}`",
        f"- completed: `{plan.completed_count}/{plan.total}`",
        f"- remaining_count: `{plan.remaining_count}`",
        f"- blocked_count: `{plan.blocked_count}`",
        f"- limit: `{plan.limit if plan.limit is not None else 'all'}`",
        f"- returned_count: `{plan.returned_count}`",
        f"- offset: `{plan.offset}`",
        f"- next_offset: `{plan.next_offset}`",
        f"- has_more: `{str(plan.has_more).lower()}`",
        f"- reviewer: {markdown_code_span(plan.reviewer)}",
        f"- pr_url: {markdown_code_span(plan.pr_url)}",
        "",
        "## Reviewer Instructions",
        "",
        "1. Run the manual check for each incomplete item below.",
        "2. Attach only non-secret proof, such as a path, PR comment, workflow URL, or sanitized log.",
        "3. Use the pass command only after reviewing real evidence.",
        "4. Use the block command when the check was attempted but cannot pass in this environment.",
        "5. Run `ai-dememory acceptance verify` after recording reviewed evidence.",
        "",
    ]

    incomplete = [item for item in plan.items if not item.completed]
    lines.extend(["## Incomplete Items", ""])
    if not incomplete:
        lines.extend(["_All manual acceptance items have reviewed passing evidence._", ""])
    for item in incomplete:
        lines.extend(
            [
                f"### {item.id}",
                "",
                f"- status: `{item.status}`",
                f"- description: {item.description}",
                f"- next action: {item.next_action}",
                "",
                "Reviewer Fill-In:",
                "",
                "- Reviewer:",
                "- Date:",
                "- Evidence reviewed:",
                "- Decision:",
                "- Notes:",
                "",
                "Suggested Artifacts:",
                "",
            ]
        )
        lines.extend(f"- {artifact}" for artifact in item.suggested_artifacts)
        lines.append("")
        if item.pass_command:
            lines.extend(["Pass Command:", "", "```bash", item.pass_command, "```", ""])
        if item.blocked_command:
            lines.extend(["Block Command:", "", "```bash", item.blocked_command, "```", ""])

    completed = [item for item in plan.items if item.completed]
    lines.extend(["## Completed Items", ""])
    if not completed:
        lines.extend(["_No manual acceptance items have reviewed passing evidence yet._", ""])
    for item in completed:
        lines.extend(
            [
                f"- `{item.id}`: {item.description}",
            ]
        )
    if completed:
        lines.append("")

    lines.extend(["## Final Gates", ""])
    lines.extend(f"- {action}" for action in plan.next_actions)
    lines.extend(
        [
            "- `ai-dememory acceptance verify` must exit zero before release sign-off.",
            "- `ai-dememory release-evidence --strict` must exit zero before release sign-off.",
            "",
            "## Boundaries",
            "",
            "- This is a generated review packet under `reports/`.",
            "- It is not acceptance evidence and does not count as a reviewed record.",
            "- It must not include secrets, tokens, cookies, private keys, or `.env` content.",
            "- Evidence is recorded only by `ai-dememory acceptance record` after human review.",
            "",
        ]
    )
    return "\n".join(lines)


def write_acceptance_packet_report(
    root: Path,
    plan: AcceptancePlan,
    report_path: str | Path = DEFAULT_ACCEPTANCE_PACKET_REPORT,
) -> Path:
    target = resolve_acceptance_packet_report_path(root, report_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    text = render_acceptance_packet_report(plan)
    if scan_text(text, "<manual-acceptance-packet-report>"):
        raise ValueError("acceptance packet report rejected by secret scan")
    target.write_text(text, encoding="utf-8")
    return target


def resolve_acceptance_packet_report_path(root: Path, report_path: str | Path = DEFAULT_ACCEPTANCE_PACKET_REPORT) -> Path:
    return resolve_acceptance_generated_report_path(root, report_path)


def resolve_acceptance_generated_report_path(root: Path, report_path: str | Path) -> Path:
    root_abs = Path(os.path.abspath(root))
    candidate = Path(report_path)
    if not candidate.is_absolute():
        candidate = root_abs / candidate
    target = Path(os.path.abspath(candidate))
    reports_root = Path(os.path.abspath(root_abs / "reports"))
    try:
        target.relative_to(root_abs)
    except ValueError as exc:
        raise ValueError("report path must stay inside the memory root") from exc
    try:
        target.relative_to(reports_root)
    except ValueError as exc:
        raise ValueError("report path must stay under reports/") from exc
    reject_acceptance_packet_symlink_components(root_abs, target, "report path")
    return target


def reject_acceptance_packet_symlink_components(root_abs: Path, target: Path, label: str) -> None:
    current = root_abs
    for part in target.relative_to(root_abs).parts:
        current = current / part
        if current.is_symlink():
            raise ValueError(f"{label} must not contain symlinks")


def resolve_acceptance_packet_archive_dir(
    root: Path,
    archive_dir: str | Path = DEFAULT_ACCEPTANCE_PACKET_ARCHIVE_DIR,
) -> Path:
    root_abs = Path(os.path.abspath(root))
    candidate = Path(archive_dir)
    if not candidate.is_absolute():
        candidate = root_abs / candidate
    target_dir = Path(os.path.abspath(candidate))
    allowed_dir = Path(os.path.abspath(root_abs / DEFAULT_ACCEPTANCE_PACKET_ARCHIVE_DIR))
    try:
        target_dir.relative_to(root_abs)
    except ValueError as exc:
        raise ValueError("archive dir must stay inside the memory root") from exc
    try:
        target_dir.relative_to(allowed_dir)
    except ValueError as exc:
        raise ValueError("archive dir must stay under reports/manual-acceptance-packets") from exc
    reject_acceptance_packet_symlink_components(root_abs, target_dir, "archive dir")
    return target_dir


def acceptance_packet_archive_path(
    root: Path,
    archive_dir: str | Path = DEFAULT_ACCEPTANCE_PACKET_ARCHIVE_DIR,
    *,
    now: datetime | None = None,
) -> Path:
    target_dir = resolve_acceptance_packet_archive_dir(root, archive_dir)
    timestamp = (now or datetime.now(timezone.utc)).strftime("%Y%m%dT%H%M%SZ")
    candidate = target_dir / f"manual-acceptance-packet-{timestamp}.md"
    suffix = 1
    while candidate.exists():
        candidate = target_dir / f"manual-acceptance-packet-{timestamp}-{suffix}.md"
        suffix += 1
    return candidate


def write_acceptance_packet_archive(
    root: Path,
    plan: AcceptancePlan,
    archive_dir: str | Path = DEFAULT_ACCEPTANCE_PACKET_ARCHIVE_DIR,
    *,
    now: datetime | None = None,
) -> Path:
    target = acceptance_packet_archive_path(root, archive_dir, now=now)
    target.parent.mkdir(parents=True, exist_ok=True)
    text = render_acceptance_packet_report(plan)
    if scan_text(text, "<manual-acceptance-packet-archive>"):
        raise ValueError("acceptance packet archive rejected by secret scan")
    target.write_text(text, encoding="utf-8")
    return target


def acceptance_packet_archive_generated_at(path: Path) -> str | None:
    match = re.fullmatch(r"manual-acceptance-packet-(\d{8}T\d{6}Z)(?:-\d+)?\.md", path.name)
    if not match:
        return None
    try:
        generated = datetime.strptime(match.group(1), "%Y%m%dT%H%M%SZ").replace(tzinfo=timezone.utc)
    except ValueError:
        return None
    return generated.isoformat().replace("+00:00", "Z")


def acceptance_packet_archive_sort_key(path: Path) -> tuple[bool, str, int, str]:
    match = re.fullmatch(r"manual-acceptance-packet-(\d{8}T\d{6}Z)(?:-(\d+))?\.md", path.name)
    if not match:
        return (False, "", -1, path.name)
    suffix = int(match.group(2) or 0)
    return (True, match.group(1), suffix, path.name)


def acceptance_packet_archive_entries(
    root: Path,
    archive_dir: str | Path = DEFAULT_ACCEPTANCE_PACKET_ARCHIVE_DIR,
) -> tuple[Path, list[AcceptancePacketArchiveEntry]]:
    target_dir = resolve_acceptance_packet_archive_dir(root, archive_dir)
    entries: list[AcceptancePacketArchiveEntry] = []
    if target_dir.exists():
        for path in sorted(target_dir.glob("*.md"), key=acceptance_packet_archive_sort_key, reverse=True):
            stat = path.stat()
            entries.append(
                AcceptancePacketArchiveEntry(
                    path=repo_relative_path(path, root),
                    size_bytes=stat.st_size,
                    modified_at=datetime.fromtimestamp(stat.st_mtime, timezone.utc).isoformat().replace("+00:00", "Z"),
                    generated_at=acceptance_packet_archive_generated_at(path),
                )
            )
    return target_dir, entries


def acceptance_packet_archive_status(
    root: Path,
    archive_dir: str | Path = DEFAULT_ACCEPTANCE_PACKET_ARCHIVE_DIR,
    *,
    limit: int = 50,
    offset: int = 0,
) -> dict[str, Any]:
    if limit < 1:
        raise ValueError("limit must be >= 1")
    if offset < 0:
        raise ValueError("offset must be >= 0")

    target_dir, entries = acceptance_packet_archive_entries(root, archive_dir)

    page = entries[offset : offset + limit]
    next_offset = offset + len(page)
    has_more = next_offset < len(entries)
    return {
        "archive_root": repo_relative_path(target_dir, root),
        "total_count": len(entries),
        "limit": limit,
        "offset": offset,
        "returned_count": len(page),
        "next_offset": next_offset if has_more else None,
        "has_more": has_more,
        "archives": [asdict(entry) for entry in page],
        "mutates_system": False,
        "records_evidence": False,
        "writes_files": False,
        "writes_acceptance_records": False,
    }


def acceptance_packet_archive_retention_plan(
    root: Path,
    archive_dir: str | Path = DEFAULT_ACCEPTANCE_PACKET_ARCHIVE_DIR,
    *,
    keep: int = 30,
    limit: int = 50,
    offset: int = 0,
) -> dict[str, Any]:
    if keep < 1:
        raise ValueError("keep must be >= 1")
    if limit < 1:
        raise ValueError("limit must be >= 1")
    if offset < 0:
        raise ValueError("offset must be >= 0")

    target_dir, entries = acceptance_packet_archive_entries(root, archive_dir)
    prune_candidates = entries[keep:]
    page = prune_candidates[offset : offset + limit]
    next_offset = offset + len(page)
    has_more = next_offset < len(prune_candidates)
    return {
        "archive_root": repo_relative_path(target_dir, root),
        "total_count": len(entries),
        "keep": keep,
        "retained_count": min(keep, len(entries)),
        "prunable_count": len(prune_candidates),
        "limit": limit,
        "offset": offset,
        "returned_count": len(page),
        "next_offset": next_offset if has_more else None,
        "has_more": has_more,
        "prune_candidates": [asdict(entry) for entry in page],
        "mutates_system": False,
        "records_evidence": False,
        "writes_files": False,
        "deletes_files": False,
        "writes_acceptance_records": False,
    }


def acceptance_template(
    item_id: str,
    status: str = "passed",
    reviewer: str | None = None,
    pr_url: str | None = None,
) -> AcceptanceTemplate:
    validate_item(item_id)
    if status not in STATUSES:
        raise ValueError("status must be passed or blocked")
    clean_reviewer = reviewer.strip() if isinstance(reviewer, str) and reviewer.strip() else None
    clean_pr_url = pr_url.strip() if isinstance(pr_url, str) and pr_url.strip() else None
    command = acceptance_record_command(item_id, status=status, reviewer=clean_reviewer, pr_url=clean_pr_url)
    artifacts = SUGGESTED_ACCEPTANCE_ARTIFACTS[item_id]
    artifact_lines = "\n".join(f"- [ ] {artifact}" for artifact in artifacts)
    markdown = f"""# Manual Acceptance Evidence Template: {item_id}

Status: `{status}`
Reviewer: {markdown_code_span(clean_reviewer)}
PR URL: {markdown_code_span(clean_pr_url)}

## Check

{ACCEPTANCE_ITEMS[item_id]}

## Suggested Artifacts

{artifact_lines}

## Review Notes

- Reviewer:{' ' + markdown_code_span(clean_reviewer) if clean_reviewer else ''}
- Date:
- Summary:
- Artifact path or URL:{' ' + markdown_code_span(clean_pr_url) if clean_pr_url else ''}

## Record Command

```bash
{command}
```

This template is not acceptance evidence until a reviewer runs the record
command with real reviewed details.
"""
    return AcceptanceTemplate(
        item=item_id,
        description=ACCEPTANCE_ITEMS[item_id],
        status=status,
        reviewer=clean_reviewer,
        pr_url=clean_pr_url,
        suggested_artifacts=artifacts,
        command=command,
        markdown=markdown,
        mutates_system=False,
        writes_files=False,
        records_evidence=False,
    )


def acceptance_plan(root: Path, reviewer: str | None = None, pr_url: str | None = None) -> AcceptancePlan:
    items = acceptance_status(root)
    plan_items: list[AcceptancePlanItem] = []
    blocked_count = 0
    completed_count = 0
    remaining_count = 0
    clean_reviewer = reviewer.strip() if isinstance(reviewer, str) and reviewer.strip() else None
    clean_pr_url = pr_url.strip() if isinstance(pr_url, str) and pr_url.strip() else None

    for item in items:
        latest = asdict(item.records[-1]) if item.records else None
        has_blocked = any(record.status == "blocked" for record in item.records)
        if item.completed:
            status = "passed"
            completed_count += 1
            pass_command = None
            blocked_command = None
            next_action = "No action required; reviewed passing evidence exists."
        elif has_blocked:
            status = "blocked"
            blocked_count += 1
            remaining_count += 1
            pass_command = acceptance_record_command(item.id, reviewer=clean_reviewer, pr_url=clean_pr_url)
            blocked_command = acceptance_record_command(
                item.id,
                "blocked",
                reviewer=clean_reviewer,
                pr_url=clean_pr_url,
            )
            next_action = "Resolve the blocker, then record reviewed passing evidence."
        else:
            status = "remaining"
            remaining_count += 1
            pass_command = acceptance_record_command(item.id, reviewer=clean_reviewer, pr_url=clean_pr_url)
            blocked_command = acceptance_record_command(
                item.id,
                "blocked",
                reviewer=clean_reviewer,
                pr_url=clean_pr_url,
            )
            next_action = "Run the manual check, review the evidence, then record the result."
        plan_items.append(
            AcceptancePlanItem(
                id=item.id,
                description=item.description,
                status=status,
                completed=item.completed,
                record_count=len(item.records),
                latest_record=latest,
                suggested_artifacts=SUGGESTED_ACCEPTANCE_ARTIFACTS[item.id],
                pass_command=pass_command,
                blocked_command=blocked_command,
                next_action=next_action,
            )
        )

    next_actions: list[str] = []
    if remaining_count:
        next_actions.append("Complete remaining manual acceptance checks before marking v2 release-ready.")
    if blocked_count:
        next_actions.append("Re-run blocked checks when their environment or external dependency is available.")
    if not remaining_count:
        next_actions.append("Run `ai-dememory acceptance verify` and `ai-dememory release-evidence --strict`.")

    return AcceptancePlan(
        complete=remaining_count == 0,
        total=len(items),
        completed_count=completed_count,
        blocked_count=blocked_count,
        remaining_count=remaining_count,
        items=plan_items,
        next_actions=next_actions,
        returned_count=len([item for item in plan_items if not item.completed]),
        reviewer=clean_reviewer,
        pr_url=clean_pr_url,
    )


def paginate_acceptance_packet_plan(plan: AcceptancePlan, limit: int = 50, offset: int = 0) -> AcceptancePlan:
    if limit < 1:
        raise ValueError("limit must be >= 1")
    if offset < 0:
        raise ValueError("offset must be >= 0")
    incomplete = [item for item in plan.items if not item.completed]
    completed = [item for item in plan.items if item.completed]
    page = incomplete[offset : offset + limit]
    next_offset = offset + len(page)
    has_more = next_offset < len(incomplete)
    return replace(
        plan,
        items=[*page, *completed],
        limit=limit,
        offset=offset,
        returned_count=len(page),
        next_offset=next_offset if has_more else None,
        has_more=has_more,
    )


def annotate_acceptance_packet_plan(
    plan: AcceptancePlan,
    reviewer: str | None = None,
    pr_url: str | None = None,
) -> AcceptancePlan:
    clean_reviewer = reviewer.strip() if isinstance(reviewer, str) and reviewer.strip() else None
    clean_pr_url = pr_url.strip() if isinstance(pr_url, str) and pr_url.strip() else None
    return replace(plan, reviewer=clean_reviewer, pr_url=clean_pr_url)


def status_to_dict(items: list[AcceptanceItemStatus]) -> list[dict[str, Any]]:
    return [
        {
            "id": item.id,
            "description": item.description,
            "completed": item.completed,
            "records": [asdict(record) for record in item.records],
        }
        for item in items
    ]


def print_status(items: list[AcceptanceItemStatus]) -> None:
    for item in items:
        mark = "x" if item.completed else " "
        print(f"[{mark}] {item.id}: {item.description}")
        for record in item.records:
            print(f"    - {record.status} by {record.reviewed_by} on {record.reviewed_at}: {record.path}")


def print_verification(verification: AcceptanceVerification) -> None:
    print(f"Manual acceptance complete: {str(verification.complete).lower()}")
    print(f"Completed: {len(verification.completed)}/{verification.total}")
    if verification.blocked:
        print("Blocked:")
        for item in verification.blocked:
            print(f"  - {item['id']}: {item['description']}")
    if verification.remaining:
        print("Remaining:")
        for item in verification.remaining:
            print(f"  - {item['id']}: {item['description']}")


def print_plan(plan: AcceptancePlan) -> None:
    print(
        "Manual acceptance plan: "
        f"{plan.completed_count}/{plan.total} complete, "
        f"{plan.remaining_count} remaining, {plan.blocked_count} blocked."
    )
    for item in plan.items:
        if item.status == "passed":
            continue
        print(f"- {item.id} ({item.status}): {item.description}")
        print(f"  next: {item.next_action}")
        if item.suggested_artifacts:
            print("  suggested artifacts:")
            for artifact in item.suggested_artifacts:
                print(f"    - {artifact}")
        if item.pass_command:
            print(f"  pass: {item.pass_command}")
        if item.blocked_command:
            print(f"  block: {item.blocked_command}")
    for action in plan.next_actions:
        print(f"- {action}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=None, help="Repository root. Defaults to this repo.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    list_cmd = subparsers.add_parser("list", help="List manual acceptance items.")
    list_cmd.add_argument("--json", action="store_true")

    status_cmd = subparsers.add_parser("status", help="Show recorded manual acceptance evidence.")
    status_cmd.add_argument("--json", action="store_true")

    plan = subparsers.add_parser("plan", help="Plan remaining manual acceptance work without recording evidence.")
    plan.add_argument("--json", action="store_true")
    plan.add_argument("--reviewer", default=None, help="Optional reviewer name to pre-fill record commands.")
    plan.add_argument("--pr-url", default=None, help="Optional PR URL to pre-fill record command artifacts.")
    plan.add_argument("--write-report", action="store_true", help="Write reports/manual-acceptance-plan.md.")
    plan.add_argument("--report-path", default=str(DEFAULT_ACCEPTANCE_PLAN_REPORT), help="Report path inside the memory root.")

    packet = subparsers.add_parser("packet", help="Generate a manual acceptance review packet without recording evidence.")
    packet.add_argument("--json", action="store_true")
    packet.add_argument("--limit", type=int, default=50, help="Maximum incomplete acceptance items to include.")
    packet.add_argument("--offset", type=int, default=0, help="Incomplete acceptance item offset for packet pagination.")
    packet.add_argument("--reviewer", default=None, help="Optional reviewer name to pre-fill the packet header.")
    packet.add_argument("--pr-url", default=None, help="Optional PR URL to pre-fill the packet header.")
    packet.add_argument("--write-report", action="store_true", help="Write reports/manual-acceptance-packet.md.")
    packet.add_argument("--report-path", default=str(DEFAULT_ACCEPTANCE_PACKET_REPORT), help="Packet path inside the memory root.")
    packet.add_argument("--archive", action="store_true", help="Write a timestamped packet copy under reports/manual-acceptance-packets/.")
    packet.add_argument("--archive-dir", default=str(DEFAULT_ACCEPTANCE_PACKET_ARCHIVE_DIR), help="Archive directory under reports/manual-acceptance-packets/.")

    packet_archive_status = subparsers.add_parser(
        "packet-archive-status",
        help="List generated manual acceptance packet archives without recording evidence.",
    )
    packet_archive_status.add_argument("--archive-dir", default=str(DEFAULT_ACCEPTANCE_PACKET_ARCHIVE_DIR))
    packet_archive_status.add_argument("--limit", type=int, default=50)
    packet_archive_status.add_argument("--offset", type=int, default=0)
    packet_archive_status.add_argument("--json", action="store_true")

    packet_archive_retention = subparsers.add_parser(
        "packet-archive-retention-plan",
        help="Plan generated manual acceptance packet archive pruning without deleting files.",
    )
    packet_archive_retention.add_argument("--archive-dir", default=str(DEFAULT_ACCEPTANCE_PACKET_ARCHIVE_DIR))
    packet_archive_retention.add_argument("--keep", type=int, default=30, help="Newest archive files to retain.")
    packet_archive_retention.add_argument("--limit", type=int, default=50)
    packet_archive_retention.add_argument("--offset", type=int, default=0)
    packet_archive_retention.add_argument("--json", action="store_true")

    template = subparsers.add_parser("template", help="Print an acceptance evidence template without recording evidence.")
    template.add_argument("--item", required=True, choices=sorted(ACCEPTANCE_ITEMS))
    template.add_argument("--status", choices=sorted(STATUSES), default="passed")
    template.add_argument("--reviewer", default=None, help="Optional reviewer name to pre-fill the record command.")
    template.add_argument("--pr-url", default=None, help="Optional PR URL to pre-fill the record command artifact.")
    template.add_argument("--json", action="store_true")

    verify = subparsers.add_parser("verify", help="Fail until every manual acceptance item has reviewed passed evidence.")
    verify.add_argument("--json", action="store_true")

    record = subparsers.add_parser("record", help="Record reviewed manual acceptance evidence.")
    record.add_argument("--item", required=True, choices=sorted(ACCEPTANCE_ITEMS))
    record.add_argument("--status", choices=sorted(STATUSES), default="passed")
    record.add_argument("--reviewed-by", required=True)
    record.add_argument("--summary", required=True)
    record.add_argument("--artifact", action="append", default=[])
    record.add_argument("--json", action="store_true")

    args = parser.parse_args(argv)
    root = repo_root(args.root)

    if args.command in {"list", "status"}:
        items = acceptance_status(root)
        if args.json:
            print(json.dumps(status_to_dict(items), indent=2))
        else:
            print_status(items)
        return 0

    if args.command == "plan":
        result = acceptance_plan(root, reviewer=args.reviewer, pr_url=args.pr_url)
        report_path: Path | None = None
        if args.write_report:
            try:
                report_path = write_acceptance_plan_report(root, result, args.report_path)
            except ValueError as exc:
                print(str(exc), file=sys.stderr)
                return 1
        if args.json:
            payload = asdict(result)
            if report_path is not None:
                payload["report_path"] = repo_relative_path(report_path, root)
            print(json.dumps(payload, indent=2))
        else:
            print_plan(result)
            if report_path is not None:
                print(f"Wrote {repo_relative_path(report_path, root)}")
        return 0

    if args.command == "packet":
        try:
            result = paginate_acceptance_packet_plan(acceptance_plan(root), limit=args.limit, offset=args.offset)
            result = annotate_acceptance_packet_plan(result, reviewer=args.reviewer, pr_url=args.pr_url)
        except ValueError as exc:
            print(str(exc), file=sys.stderr)
            return 1
        markdown = render_acceptance_packet_report(result)
        report_path: Path | None = None
        archive_path: Path | None = None
        if args.archive:
            try:
                acceptance_packet_archive_path(root, args.archive_dir)
            except ValueError as exc:
                print(str(exc), file=sys.stderr)
                return 1
        if args.write_report:
            try:
                report_path = write_acceptance_packet_report(root, result, args.report_path)
            except ValueError as exc:
                print(str(exc), file=sys.stderr)
                return 1
        if args.archive:
            try:
                archive_path = write_acceptance_packet_archive(root, result, args.archive_dir)
            except ValueError as exc:
                print(str(exc), file=sys.stderr)
                return 1
        if args.json:
            payload: dict[str, Any] = {
                "complete": result.complete,
                "total": result.total,
                "completed_count": result.completed_count,
                "blocked_count": result.blocked_count,
                "remaining_count": result.remaining_count,
                "limit": result.limit,
                "returned_count": result.returned_count,
                "offset": result.offset,
                "next_offset": result.next_offset,
                "has_more": result.has_more,
                "reviewer": result.reviewer,
                "pr_url": result.pr_url,
                "items": [asdict(item) for item in result.items if not item.completed],
                "mutates_system": False,
                "records_evidence": False,
                "writes_acceptance_records": False,
                "writes_files": report_path is not None or archive_path is not None,
                "writes_archive": archive_path is not None,
                "report_path": repo_relative_path(report_path, root) if report_path is not None else None,
                "archive_path": repo_relative_path(archive_path, root) if archive_path is not None else None,
                "markdown": markdown,
            }
            print(json.dumps(payload, indent=2))
        else:
            print(markdown, end="")
            if report_path is not None:
                print(f"Wrote {repo_relative_path(report_path, root)}")
            if archive_path is not None:
                print(f"Archived {repo_relative_path(archive_path, root)}")
        return 0

    if args.command == "packet-archive-status":
        try:
            payload = acceptance_packet_archive_status(
                root,
                archive_dir=args.archive_dir,
                limit=args.limit,
                offset=args.offset,
            )
        except ValueError as exc:
            print(str(exc), file=sys.stderr)
            return 1
        if args.json:
            print(json.dumps(payload, indent=2))
        else:
            print(f"Archive: {payload['archive_root']}")
            print(f"Archives: {payload['returned_count']}/{payload['total_count']}")
            for archive in payload["archives"]:
                generated_at = archive["generated_at"] or "unknown"
                print(f"- {archive['path']} ({archive['size_bytes']} bytes, generated_at={generated_at})")
            if payload["has_more"]:
                print(f"Next offset: {payload['next_offset']}")
        return 0

    if args.command == "packet-archive-retention-plan":
        try:
            payload = acceptance_packet_archive_retention_plan(
                root,
                archive_dir=args.archive_dir,
                keep=args.keep,
                limit=args.limit,
                offset=args.offset,
            )
        except ValueError as exc:
            print(str(exc), file=sys.stderr)
            return 1
        if args.json:
            print(json.dumps(payload, indent=2))
        else:
            print(f"Archive: {payload['archive_root']}")
            print(f"Retention: keep newest {payload['keep']} of {payload['total_count']} archive(s)")
            print(f"Prune candidates: {payload['returned_count']}/{payload['prunable_count']}")
            for archive in payload["prune_candidates"]:
                generated_at = archive["generated_at"] or "unknown"
                print(f"- {archive['path']} ({archive['size_bytes']} bytes, generated_at={generated_at})")
            if payload["has_more"]:
                print(f"Next offset: {payload['next_offset']}")
        return 0

    if args.command == "template":
        result = acceptance_template(args.item, status=args.status, reviewer=args.reviewer, pr_url=args.pr_url)
        if args.json:
            print(json.dumps(asdict(result), indent=2))
        else:
            print(result.markdown, end="")
        return 0

    if args.command == "verify":
        verification = verify_acceptance(acceptance_status(root))
        if args.json:
            print(json.dumps(asdict(verification), indent=2))
        else:
            print_verification(verification)
        return 0 if verification.complete else 1

    try:
        path = record_acceptance(
            root,
            args.item,
            args.status,
            args.reviewed_by,
            args.summary,
            artifacts=args.artifact,
        )
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    relpath = repo_relative_path(path, root)
    if args.json:
        print(json.dumps({"path": relpath}, indent=2))
    else:
        print(f"Wrote {relpath}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
