#!/usr/bin/env python3
"""Validate that the v2 release checklist lists current release gates."""

from __future__ import annotations

import argparse
from dataclasses import asdict, dataclass
import json
from pathlib import Path
import re
import sys

from memorylib import repo_root


CHECKLIST_PATH = Path("docs/release-v2-checklist.md")

REQUIRED_HEADINGS = {
    "repository": "## Repository State",
    "static": "## Static Checks",
    "package": "## Package Install Smoke",
    "docker": "## Docker Local MCP Smoke",
    "publishing": "## Publishing",
    "artifacts": "## Generated Artifacts",
    "mcp_runtime": "## MCP Runtime Smoke",
    "security": "## Security Review",
    "manual": "## Manual Acceptance",
}

REQUIRED_SNIPPETS = {
    "doctor": "python3 scripts/ai_dememory.py doctor",
    "doctor_summary": "python3 scripts/ai_dememory.py doctor --json --summary",
    "profile_aware_doctor": "only an initial missing-index warning",
    "verify_mcp": "python3 scripts/ai_dememory.py verify-mcp",
    "mcp_inventory": "python3 scripts/ai_dememory.py mcp-inventory --check-docs",
    "ci_guard": "python3 scripts/ai_dememory.py ci-guard",
    "artifact_guard": "python3 scripts/ai_dememory.py artifact-guard",
    "ci_post_smoke_artifact_guard": "CI runs `python scripts/ai_dememory.py package-build-smoke --check-clean`",
    "vault_setup_guard": "python3 scripts/ai_dememory.py vault-setup-guard",
    "pr_template_guard": "python3 scripts/ai_dememory.py pr-template-guard",
    "pr_draft_guard": "python3 scripts/ai_dememory.py pr-draft-guard",
    "pr_draft_guard_adr": "docs/adr/0231-pr-draft-handoff-guard.md",
    "acceptance_guard": "python3 scripts/ai_dememory.py acceptance-guard",
    "adr_guard": "python3 scripts/ai_dememory.py adr-guard",
    "release_checklist_guard": "python3 scripts/ai_dememory.py release-checklist-guard",
    "release_check": "python3 scripts/ai_dememory.py release-check",
    "roadmap_status": "python3 scripts/ai_dememory.py roadmap status --json",
    "roadmap_status_adr": "docs/adr/0232-roadmap-status.md",
    "roadmap_status_smoke_adr": "docs/adr/0234-roadmap-status-smoke.md",
    "ci_pr_gated_strict_release_check": "CI runs `python scripts/ai_dememory.py release-check --strict` on pull",
    "ci_pr_gated_mcp_smoke": "CI runs `python scripts/ai_dememory.py mcp-smoke` on pull requests",
    "api_smoke": "python3 scripts/ai_dememory.py api-smoke",
    "validate": "python3 scripts/ai_dememory.py validate",
    "validate_json": "python3 scripts/ai_dememory.py validate --json",
    "secret_scan": "python3 scripts/ai_dememory.py secret-scan",
    "eval_recall": "python3 scripts/ai_dememory.py eval-recall",
    "context": "python3 scripts/ai_dememory.py context ai-dememory --budget 2000",
    "context_auto": "python3 scripts/ai_dememory.py context --auto --budget 2000",
    "context_query_source": "query_source: working_memory",
    "recall_fixture_status": "python3 scripts/ai_dememory.py recall-fixtures status --json",
    "recall_miss_candidate_check": "python3 scripts/ai_dememory.py recall-fixtures check-miss",
    "capture_miss_dry_run": "python3 scripts/ai_dememory.py capture-miss --query \"missed query\"",
    "recall_fixture_review_plan": "python3 scripts/ai_dememory.py recall-fixtures review-plan --json",
    "recall_review_report": "python3 scripts/ai_dememory.py recall-fixtures review-plan --write-report",
    "recall_review_packet": "python3 scripts/ai_dememory.py recall-fixtures packet --write-report",
    "recall_review_packet_pagination": "python3 scripts/ai_dememory.py recall-fixtures packet --limit",
    "recall_review_packet_metadata": "python3 scripts/ai_dememory.py recall-fixtures packet --reviewer",
    "recall_review_packet_archive": "python3 scripts/ai_dememory.py recall-fixtures packet --archive --json",
    "recall_review_packet_archive_status": "python3 scripts/ai_dememory.py recall-fixtures packet-archive-status",
    "recall_review_packet_archive_retention_plan": "python3 scripts/ai_dememory.py recall-fixtures packet-archive-retention-plan",
    "mcp_recall_review_packet": "memory.recall_review_packet",
    "mcp_recall_review_packet_pagination": "pending_next_offset",
    "mcp_recall_review_packet_metadata": "memory.recall_review_packet` supports optional `reviewer` and `pr_url`",
    "mcp_recall_review_packet_archive_status": "memory.recall_review_packet_archive_status",
    "mcp_recall_review_packet_archive_retention_plan": "memory.recall_review_packet_archive_retention_plan",
    "recall_fixture_status_strict": "python3 scripts/ai_dememory.py recall-fixtures status --strict --max-age-days 14",
    "recall_fixture_promotion_closes_miss": "marks the source miss as `status: promoted`",
    "recall_fixture_promotion_passes": "validates that the fixture passes",
    "recall_miss_review_cli": "marks a reviewed miss as `rejected` or `dismissed` without writing fixtures",
    "install_smoke": "python3 scripts/ai_dememory.py install-smoke",
    "package_build_smoke": "python3 scripts/ai_dememory.py package-build-smoke",
    "package_build_stale_artifact_preflight": "package-build-smoke refuses stale generated package build artifacts",
    "install_smoke_doctor_summary": "doctor profile summary",
    "install_smoke_initialized_notification": "install smoke direct MCP payload sends `notifications/initialized`",
    "install_smoke_response_id": "install smoke direct MCP validator matches JSON-RPC responses by id",
    "install_smoke_missing_response": "install smoke direct MCP validator reports missing initialize and ping responses",
    "install_smoke_unexpected_response": "install smoke direct MCP validator rejects unexpected integer response ids",
    "install_smoke_invalid_response": "install smoke direct MCP validator rejects non-integer response ids",
    "install_smoke_duplicate_response": "install smoke direct MCP validator rejects duplicate response ids",
    "install_smoke_result_field": "install smoke direct MCP validator rejects responses missing result or error",
    "install_smoke_result_type": "install smoke direct MCP validator rejects non-object initialize and ping results",
    "install_smoke_protocol_version": "install smoke direct MCP validator reports missing and invalid initialize protocolVersion",
    "install_smoke_release_evidence": "ai-dememory mcp --call memory.release_evidence --args",
    "install_smoke_mcp_publish_plan": "ai-dememory mcp --call memory.publish_plan --args",
    "install_smoke_maintenance_status": "Installed `ai-dememory maintenance status` reports generated artifact",
    "install_smoke_maintenance_artifact_freshness": "artifact_freshness",
    "install_smoke_maintenance_review_due": "Installed and Docker `ai-dememory maintenance status` validate",
    "install_smoke_maintenance_stale_suppressions": "review_due.stale_suppressions",
    "install_smoke_maintenance_conflict_review": "conflict_review.active_conflicts",
    "install_smoke_maintenance_recommendations": "review_recommendations.pending_count",
    "install_smoke_schedule_plan": "Installed `ai-dememory schedule plan --json` validates scheduler commands",
    "docker_smoke_schedule_plan": "Docker smoke verifies `schedule plan --json` returns",
    "install_smoke_roadmap_status": "Installed `ai-dememory roadmap status --json` validates",
    "docker_smoke_roadmap_status": "Docker smoke verifies `roadmap status --json` returns",
    "mcp_maintenance_recommendations": "applies_review_decisions=false",
    "mcp_maintenance_artifact_freshness": "memory.maintenance_status` reports `artifact_freshness",
    "install_smoke_schedule_doctor": "Package install smoke runs `ai-dememory schedule doctor --json`",
    "publish_guard": "python3 scripts/ai_dememory.py publish-guard",
    "publish_plan_testpypi": "python3 scripts/ai_dememory.py publish-plan --repository testpypi --json",
    "publish_plan_pypi": "python3 scripts/ai_dememory.py publish-plan --repository pypi --json",
    "publish_plan_side_effects": "false publish side-effect flags",
    "publish_plan_workflow_url": "`workflow_url` from project metadata or the local GitHub remote",
    "release_evidence": "python3 scripts/ai_dememory.py release-evidence --json",
    "release_evidence_acceptance_plan": "manual_acceptance_plan",
    "release_evidence_blockers": "release_blockers",
    "release_evidence_next_actions": "next_actions",
    "release_evidence_recall_freshness": "recall_fixture_freshness",
    "release_evidence_recall_review_plan": "recall_fixture_review_plan",
    "release_evidence_vector_readiness": "vector_readiness",
    "release_evidence_setup_health_summary": "setup_health_summary",
    "release_evidence_maintenance_summary": "maintenance_summary",
    "release_evidence_artifact_freshness": "artifact_freshness",
    "release_evidence_recall_candidate_command": "candidate_check_command",
    "release_evidence_recall_resolved_count": "resolved_count",
    "release_evidence_handoff_commands": "`handoff_commands` for release evidence, manual acceptance, recall review",
    "release_evidence_handoff_publish_plan": "publish-plan",
    "release_evidence_handoff_publish_plan_testpypi": "publish_plan_testpypi",
    "release_evidence_handoff_publish_plan_pypi": "publish_plan_pypi",
    "release_evidence_handoff_acceptance_plan": "handoff_commands.commands.acceptance_plan",
    "release_evidence_handoff_acceptance_template": "handoff_commands.commands.acceptance_template",
    "release_evidence_reviewer_metadata_cli": "release-evidence --reviewer",
    "release_evidence_recall_blocker": "recall_fixture_review",
    "release_evidence_vector_blocker": "vector_readiness_review",
    "release_evidence_strict": "python3 scripts/ai_dememory.py release-evidence --strict",
    "release_evidence_report_path": "python3 scripts/ai_dememory.py release-evidence --write-report --report-path",
    "acceptance_status": "python3 scripts/ai_dememory.py acceptance status --json",
    "acceptance_plan": "python3 scripts/ai_dememory.py acceptance plan --json",
    "acceptance_plan_report": "python3 scripts/ai_dememory.py acceptance plan --write-report",
    "acceptance_packet_report": "python3 scripts/ai_dememory.py acceptance packet --write-report",
    "acceptance_packet_pagination": "python3 scripts/ai_dememory.py acceptance packet --limit",
    "acceptance_packet_metadata": "python3 scripts/ai_dememory.py acceptance packet --reviewer",
    "acceptance_packet_archive": "python3 scripts/ai_dememory.py acceptance packet --archive --json",
    "acceptance_packet_archive_status": "python3 scripts/ai_dememory.py acceptance packet-archive-status --json",
    "acceptance_packet_archive_retention_plan": "python3 scripts/ai_dememory.py acceptance packet-archive-retention-plan --json",
    "acceptance_plan_artifacts": "suggested_artifacts",
    "acceptance_template_cli": "python3 scripts/ai_dememory.py acceptance template --item mcp-client-installed --json",
    "acceptance_verify": "python3 scripts/ai_dememory.py acceptance verify --json",
    "mcp_client_smoke": "python3 scripts/ai_dememory.py mcp-client-smoke",
    "provenance": "python3 scripts/ai_dememory.py provenance --json",
    "provenance_report_path": "python3 scripts/ai_dememory.py provenance --write-report --report-path",
    "maintenance_lifecycle_artifacts": "indexes/memory-lifecycle.json",
    "lifecycle_report_path": "python3 scripts/ai_dememory.py lifecycle report --report-path",
    "mark_seen_receipt": "python3 scripts/ai_dememory.py mark-seen --id mem_preferences_20260614",
    "mark_seen_lifecycle_updated": "lifecycle_updated",
    "outcome_receipt": "python3 scripts/ai_dememory.py outcome --last --good --json",
    "outcome_counter": "positive_outcomes",
    "sleep_report_path": "python3 scripts/ai_dememory.py sleep plan --report-path",
    "sleep_json_report_path": "python3 scripts/ai_dememory.py sleep plan --json --json-report-path",
    "sleep_dry_run_alias": "python3 scripts/ai_dememory.py sleep --dry-run --json",
    "sleep_propose_alias": "python3 scripts/ai_dememory.py sleep --propose --id",
    "sleep_apply_reviewed_alias": "python3 scripts/ai_dememory.py sleep --apply-reviewed --id",
    "vector_status": "python3 scripts/ai_dememory.py vector status",
    "vector_report_path": "python3 scripts/ai_dememory.py vector status --write-report --report-path",
    "review_false_positives": "python3 scripts/ai_dememory.py review false-positives",
    "review_false_positives_report_path": "python3 scripts/ai_dememory.py review false-positives --report-path",
    "review_false_positives_due_only": "review false-positives --due-only",
    "review_stale_false_positives": "review stale-false-positives",
    "review_false_positive_due_status": "`review_due` and",
    "mcp_review_false_positives_due_only": "due_only=true",
    "mcp_review_stale_false_positives": "memory.review_stale_false_positives",
    "review_conflicts": "python3 scripts/ai_dememory.py review conflicts",
    "review_conflicts_report_path": "python3 scripts/ai_dememory.py review conflicts --report-path",
    "review_modes": "python3 scripts/ai_dememory.py review modes",
    "review_plan": "python3 scripts/ai_dememory.py review plan --kind conflict",
    "review_recommendation": "python3 scripts/ai_dememory.py review recommendation --kind conflict",
    "review_recommendations": "python3 scripts/ai_dememory.py review recommendations --json",
    "review_recommendation_outcome": "python3 scripts/ai_dememory.py review recommendation-outcome --id",
    "review_recommendation_link": "python3 scripts/ai_dememory.py conflict resolve --id conf_example --keep",
    "consolidation_report_path": "python3 scripts/ai_dememory.py consolidate --dry-run --report-path",
    "compileall": "python3 -m compileall -q scripts mcp/server ai_dememory_tool",
    "unit_tests": "python3 -m unittest discover -s tests",
    "docker_build": "docker build -t ai-dememory:local .",
    "docker_install_smoke": "ai-dememory install-smoke --skip-package --docker --image ai-dememory:local",
    "docker_doctor_summary": "doctor --json --summary",
    "docker_client_config_smoke": "generated Docker MCP client config",
    "docker_release_evidence": "ai-dememory:local mcp --call memory.release_evidence --args",
    "docker_mcp_publish_plan": "ai-dememory:local mcp --call memory.publish_plan --args",
    "docker_maintenance_status": "ai-dememory:local maintenance status",
    "pr_gate": "AI_DEMEMORY_PR_URL",
    "mcp_smoke": "python3 scripts/ai_dememory.py mcp-smoke",
    "mcp_runtime_paginated_tools": "Paginated `tools/list`",
    "mcp_runtime_paginated_resources": "Paginated `resources/list`",
    "mcp_runtime_paginated_prompts": "Paginated `prompts/list`",
    "mcp_runtime_initialized_notification": "notifications/initialized` before `ping",
    "mcp_runtime_response_id_smoke": "runtime smoke matches JSON-RPC responses by id",
    "mcp_runtime_list_identity": "duplicate tool names, resource URIs",
    "mcp_doctor": "memory.doctor",
    "mcp_context_auto": "auto: true",
    "maintenance_artifact_status": "generated artifact state",
    "maintenance_provider_readiness": "provider import readiness without reading provider files",
    "maintenance_review_due_status": "maintenance status` reports false-positive review due",
    "maintenance_stale_suppression_status": "stale suppression counts",
    "maintenance_conflict_review_status": "conflict review counts",
    "provider_import_dry_run": "ai-dememory import-chats codex --dry-run --json",
    "mcp_provider_import_dry_run": "memory.import_chats` accepts `dry_run=true",
    "provider_import_idempotency": "Repeated provider imports skip candidates with the same stable fingerprint",
    "mcp_recall_miss_candidate": "memory.recall_miss_candidate",
    "mcp_recall_fixture_status": "memory.recall_fixture_status",
    "mcp_recall_review_plan": "memory.recall_review_plan",
    "mcp_recall_review_resolved": "recent_resolved_misses",
    "mcp_recall_miss_review": "memory.recall_miss_review",
    "mcp_vector_status": "memory.vector_status",
    "mcp_provenance_status": "memory.provenance_status",
    "mcp_working_current": "memory.working_current",
    "mcp_working_status": "memory.working_status",
    "mcp_working_snapshot": "memory.working_snapshot",
    "mcp_working_handoff": "memory.working_handoff",
    "mcp_mark_seen_receipt": "selected_memory_id",
    "mcp_outcome_receipt": "memory.outcome",
    "mcp_outcome_target_source": "target_source",
    "mcp_false_positive_receipt": "memory.false_positive_ignore",
    "mcp_false_positive_unignore_receipt": "memory.false_positive_unignore",
    "mcp_false_positive_reviewer": "reviewer",
    "mcp_conflict_dismiss_receipt": "memory.conflict_dismiss",
    "mcp_conflict_keep": "memory.conflict_keep",
    "mcp_conflict_keep_reviewer": "reviewer",
    "mcp_conflict_keep_boundary": "canonical memory",
    "mcp_conflict_merge_receipt": "memory.conflict_merge_proposal",
    "mcp_schedule_status": "memory.schedule_status",
    "mcp_schedule_status_review_due": "review due summaries",
    "mcp_schedule_plan_cron_entries": "memory.schedule_plan` returns reviewed `cron_entries` with",
    "scheduler_input_validation": "Invalid scheduler config reports validation errors and no platform status commands",
    "mcp_schedule_validation_schema": "memory.schedule_status` output schema includes `valid` and",
    "mcp_schedule_validation_smoke": "MCP runtime smoke covers invalid scheduler config with `valid=false`",
    "schedule_environment_cli": "schedule doctor --json` reports",
    "schedule_plan_cli": "python3 scripts/ai_dememory.py schedule plan --json",
    "schedule_plan_installed": "ai-dememory schedule plan --json",
    "mcp_schedule_environment": "memory.schedule_environment` reports scheduler, Docker, and optional",
    "mcp_review_configure_mode": "memory.review_configure_mode",
    "mcp_review_recommendation": "memory.review_recommendation",
    "mcp_review_recommendations": "memory.review_recommendations",
    "mcp_review_recommendation_archive_status": "memory.review_recommendation_archive_status",
    "mcp_review_recommendation_archive_restore_preview": "memory.review_recommendation_archive_restore_preview",
    "mcp_review_recommendation_archive_recursive": "recursive=true",
    "mcp_review_recommendation_archive_pagination": "next_offset",
    "mcp_review_recommendation_archive_invalid_pagination": "invalid_next_offset",
    "mcp_review_recommendation_outcome_report": "memory.review_recommendation_outcome_report",
    "mcp_review_recommendation_outcome_report_pagination": "invalid_next_offset",
    "mcp_review_recommendation_outcome": "memory.review_recommendation_outcome",
    "mcp_review_recommendation_link": "linked recommendation metadata",
    "mcp_provider_status": "memory.providers_status",
    "mcp_provider_plan": "memory.providers_plan",
    "mcp_setup_plan": "memory.setup_plan",
    "mcp_setup_health": "memory.setup_health",
    "mcp_git_lessons": "memory.git_lessons",
    "mcp_git_lessons_dry_run": "memory.git_lessons` defaults to `dry_run=true",
    "git_lesson_idempotency": "Repeated git lesson capture skips candidates with the same stable fingerprint",
    "hook_capture_summary_cli": "python3 scripts/ai_dememory.py hooks captures --json",
    "hook_capture_summary_filters_cli": "ai-dememory hooks captures --provider <provider>",
    "hook_capture_summary_date_filters_cli": "ai-dememory hooks captures --created-from <date>",
    "hook_capture_report_cli": "python3 scripts/ai_dememory.py hooks captures --write-report",
    "hook_capture_report_installed": "ai-dememory hooks captures --write-report",
    "hook_capture_review_cli": "ai-dememory hooks review --path <capture>",
    "hook_capture_archive_preview_cli": "ai-dememory hooks archive --json",
    "hook_capture_archive_apply_cli": "ai-dememory hooks archive --apply",
    "mcp_hook_capture_review": "memory.hook_capture_review",
    "mcp_hook_capture_filters": "capture_review_status",
    "mcp_hook_capture_date_filters": "capture_created_from",
    "hook_event_idempotency": "Repeated hook captures with the same provider, event, and payload fingerprint reuse the existing inbox file",
    "hook_json_fingerprint": "Equivalent JSON hook payloads with different formatting or key order reuse the existing inbox file",
    "mcp_acceptance_plan": "memory.acceptance_plan",
    "mcp_acceptance_template": "memory.acceptance_template",
    "mcp_acceptance_packet": "memory.acceptance_packet",
    "mcp_acceptance_packet_pagination": "next_offset",
    "mcp_acceptance_packet_metadata": "memory.acceptance_packet` supports optional `reviewer` and `pr_url`",
    "mcp_acceptance_packet_archive_status": "memory.acceptance_packet_archive_status",
    "mcp_acceptance_packet_archive_retention_plan": "memory.acceptance_packet_archive_retention_plan",
    "mcp_release_evidence": "memory.release_evidence",
    "mcp_release_evidence_report": "memory.release_evidence_report",
    "mcp_release_evidence_reviewer_metadata": "memory.release_evidence` and `memory.release_evidence_report` accept",
    "mcp_publish_plan": "memory.publish_plan",
    "mcp_roadmap_status": "memory.roadmap_status",
    "testpypi": "TestPyPI",
    "pypi": "PyPI",
    "generated_artifacts": "No generated SQLite, report, cache, or distilled output is staged.",
    "search_matched_terms": "matched_terms",
    "search_matched_fields": "matched_fields",
    "working_status": "python3 scripts/ai_dememory.py working status --json",
    "maintenance_report_dir": "ai-dememory maintenance run --profile daily --report-dir reports/maintenance",
    "maintenance_dry_run": "ai-dememory maintenance run --profile daily --dry-run --json",
    "weekly_maintenance_hook_report_dry_run": "would_write_hook_capture_report=true",
    "weekly_maintenance_sleep_report_dry_run": "would_write_sleep_plan_report=true",
    "weekly_maintenance_hook_report": "ai-dememory maintenance run --profile weekly` writes",
    "weekly_maintenance_sleep_report": "reports/sleep-plan.md",
    "mcp_maintenance_run_dry_run": "memory.maintenance_run` accepts `dry_run=true",
    "manual_record": "ai-dememory acceptance record --item",
    "plugin_working_session_skill": "working-session",
    "plugin_mcp_tool_surface": "review-first plugin MCP surface",
    "plugin_server_only_tools": "server-only MCP tools",
    "plugin_tool_classification": "classified as either plugin-enabled or server-only",
    "plugin_review_receipts": "review-mode receipt tools",
    "plugin_mcp_config_smoke": "plugins/ai-dememory/.mcp.json --command",
    "plugin_enabled_tools_smoke": "enabled_tools` against paginated `tools/list",
    "plugin_single_session_pagination_smoke": "single stdio session for paginated `tools/list`",
    "mcp_client_initialized_notification_smoke": "sends `notifications/initialized` before ping",
    "mcp_client_response_id_smoke": "matches JSON-RPC responses by id",
    "readme_mcp_inventory_guard": "README.md MCP inventory",
    "private_vault_generated_artifacts": "Private vault setup does not stage generated artifact directories.",
    "vault_template_export": "ai-dememory vault-template export ./ai-dememory-vault-template",
    "install_smoke_vault_template_export": "ai-dememory vault-template export <temp-template-repo>",
    "package_build_smoke_temp": "ai-dememory package-build-smoke",
    "docker_smoke_vault_template_export": "docker run --rm -v <temp-template-repo>:/template ai-dememory:local vault-template export /template --force --json",
    "publish_workflow_preflight": "Publish workflow preflight runs `publish-guard`, `artifact-guard`, `validate`, `secret-scan`, `verify-mcp`, `release-check`, installed package",
    "package_build_smoke_adr": "docs/adr/0077-package-build-smoke.md",
    "package_build_stale_artifact_preflight_adr": "docs/adr/0105-package-build-stale-artifact-preflight.md",
    "ci_post_smoke_artifact_guard_adr": "docs/adr/0106-ci-post-smoke-artifact-guard.md",
    "ci_pr_gated_mcp_smoke_adr": "docs/adr/0107-ci-pr-gated-mcp-runtime-smoke.md",
    "docker_vault_template_export_target_adr": "docs/adr/0108-docker-vault-template-export-target.md",
    "release_evidence_without_git_adr": "docs/adr/0109-release-evidence-without-git.md",
    "publish_workflow_smoke_gates_adr": "docs/adr/0127-publish-workflow-smoke-gates.md",
    "testpypi_acceptance_publish_preflight_adr": "docs/adr/0128-testpypi-acceptance-publish-preflight.md",
    "publish_plan_adr": "docs/adr/0236-publish-plan.md",
    "capture_miss_dry_run_adr": "docs/adr/0129-capture-miss-dry-run.md",
    "recall_miss_candidate_check_adr": "docs/adr/0130-recall-miss-candidate-check.md",
    "mcp_recall_miss_candidate_adr": "docs/adr/0131-mcp-recall-miss-candidate.md",
    "recall_review_candidate_guidance_adr": "docs/adr/0132-recall-review-candidate-guidance.md",
    "release_evidence_recall_freshness_adr": "docs/adr/0110-release-evidence-recall-freshness.md",
    "release_evidence_recall_review_plan_adr": "docs/adr/0111-release-evidence-recall-review-plan.md",
    "release_evidence_vector_readiness_adr": "docs/adr/0184-release-evidence-vector-readiness.md",
    "release_evidence_setup_health_summary_adr": "docs/adr/0185-release-evidence-setup-health-summary.md",
    "release_evidence_maintenance_summary_adr": "docs/adr/0222-release-evidence-maintenance-summary.md",
    "release_evidence_handoff_commands_adr": "docs/adr/0235-release-evidence-handoff-commands.md",
    "recall_promotion_closes_source_miss_adr": "docs/adr/0112-recall-promotion-closes-source-miss.md",
    "recall_miss_review_outcomes_adr": "docs/adr/0113-recall-miss-review-outcomes.md",
    "recall_review_resolved_summary_adr": "docs/adr/0114-recall-review-resolved-summary.md",
    "recall_review_plan_report_adr": "docs/adr/0115-recall-review-plan-report.md",
    "recall_review_packet_adr": "docs/adr/0187-recall-review-packet.md",
    "mcp_recall_review_packet_adr": "docs/adr/0193-mcp-recall-review-packet.md",
    "recall_review_packet_pagination_adr": "docs/adr/0207-recall-review-packet-pagination.md",
    "recall_review_packet_metadata_adr": "docs/adr/0210-recall-review-packet-metadata.md",
    "recall_review_packet_archive_adr": "docs/adr/0212-recall-review-packet-archive.md",
    "recall_review_packet_archive_status_adr": "docs/adr/0214-recall-review-packet-archive-status.md",
    "mcp_recall_review_packet_archive_status_adr": "docs/adr/0216-mcp-recall-review-packet-archive-status.md",
    "generated_packet_archive_retention_plan_adr": "docs/adr/0218-generated-packet-archive-retention-plan.md",
    "manual_acceptance_plan_report_adr": "docs/adr/0116-manual-acceptance-plan-report.md",
    "manual_acceptance_plan_metadata": "acceptance plan --reviewer",
    "manual_acceptance_template_metadata": "acceptance template --item",
    "mcp_acceptance_plan_template_metadata": "memory.acceptance_plan` and `memory.acceptance_template` support optional",
    "manual_acceptance_packet_adr": "docs/adr/0186-manual-acceptance-packet.md",
    "mcp_manual_acceptance_packet_adr": "docs/adr/0192-mcp-manual-acceptance-packet.md",
    "manual_acceptance_packet_pagination_adr": "docs/adr/0208-manual-acceptance-packet-pagination.md",
    "manual_acceptance_packet_metadata_adr": "docs/adr/0209-manual-acceptance-packet-metadata.md",
    "manual_acceptance_packet_archive_adr": "docs/adr/0211-manual-acceptance-packet-archive.md",
    "manual_acceptance_packet_archive_status_adr": "docs/adr/0213-manual-acceptance-packet-archive-status.md",
    "mcp_manual_acceptance_packet_archive_status_adr": "docs/adr/0215-mcp-manual-acceptance-packet-archive-status.md",
    "mcp_release_evidence_report_adr": "docs/adr/0194-mcp-release-evidence-report.md",
    "mcp_roadmap_status_adr": "docs/adr/0233-mcp-roadmap-status.md",
    "mcp_publish_plan_adr": "docs/adr/0237-mcp-publish-plan.md",
    "mcp_publish_plan_smoke_adr": "docs/adr/0238-mcp-publish-plan-smoke.md",
    "release_evidence_publish_plan_commands_adr": "docs/adr/0239-release-evidence-publish-plan-commands.md",
    "publish_plan_workflow_url_adr": "docs/adr/0240-publish-plan-workflow-url.md",
    "plugin_server_only_tool_classification_adr": "docs/adr/0241-plugin-server-only-tool-classification.md",
    "acceptance_plan_template_metadata_adr": "docs/adr/0242-acceptance-plan-template-metadata.md",
    "release_evidence_acceptance_metadata_adr": "docs/adr/0243-release-evidence-acceptance-metadata.md",
    "acceptance_command_safe_quoting_adr": "docs/adr/0244-acceptance-command-safe-quoting.md",
    "release_evidence_report_path_guard_adr": "docs/adr/0118-release-evidence-report-path-guard.md",
    "vector_readiness_report_path_guard_adr": "docs/adr/0119-vector-readiness-report-path-guard.md",
    "durable_provenance_report_path_guard_adr": "docs/adr/0120-durable-provenance-report-path-guard.md",
    "lifecycle_report_path_guard_adr": "docs/adr/0121-lifecycle-report-path-guard.md",
    "sleep_plan_report_path_guard_adr": "docs/adr/0122-sleep-plan-report-path-guard.md",
    "consolidation_report_path_guard_adr": "docs/adr/0123-consolidation-report-path-guard.md",
    "review_report_path_guard_adr": "docs/adr/0124-review-report-path-guard.md",
    "maintenance_report_dir_guard_adr": "docs/adr/0125-maintenance-report-dir-guard.md",
    "recall_review_report_secret_scan_adr": "docs/adr/0126-recall-review-report-secret-scan.md",
    "provider_setup_plan_adr": "docs/adr/0078-provider-setup-plan.md",
    "provider_configure_dry_run_adr": "docs/adr/0228-provider-configure-dry-run.md",
    "provider_setup_plan_cli": "python3 scripts/ai_dememory.py providers plan --json",
    "provider_configure_dry_run_cli": "providers configure codex --path",
    "provider_configure_dry_run_flag": "--dry-run --json",
    "provider_setup_plan_installed": "ai-dememory providers plan --json",
    "provider_configure_dry_run_contract": "configure_dry_run_command",
    "local_setup_plan_adr": "docs/adr/0079-local-setup-plan.md",
    "local_setup_plan_cli": "python3 scripts/ai_dememory.py setup plan --json",
    "local_setup_plan_installed": "ai-dememory setup plan --json",
    "setup_health_cli": "python3 scripts/ai_dememory.py setup health --json",
    "setup_health_validation_status": "validation_status",
    "setup_health_context_config": "context_config",
    "setup_health_manual_acceptance": "manual_acceptance",
    "setup_health_vector_readiness": "vector_readiness",
    "setup_health_recall_review": "recall_review",
    "setup_health_generated_packet_archives": "generated_packet_archives",
    "maintenance_generated_packet_archives": "generated packet archive cleanup",
    "setup_health_maintenance_preflight": "maintenance preflight commands",
    "local_setup_plan_generated_reports": "generated_reports",
    "local_setup_plan_generated_archive_status": "generated_archive_status",
    "local_setup_plan_generated_archive_retention": "generated_archive_retention",
    "local_setup_plan_schedule_plan": "includes installed and Docker `schedule plan --json` command arrays",
    "local_setup_plan_cron_commands": "includes installed and Docker `schedule cron` command arrays",
    "local_setup_plan_schedule_doctor": "includes installed and Docker `schedule doctor --json`",
    "setup_plan_generated_reports_adr": "docs/adr/0117-setup-plan-generated-reports.md",
    "setup_plan_generated_archive_status_adr": "docs/adr/0217-setup-plan-generated-archive-status.md",
    "setup_plan_generated_archive_retention_adr": "docs/adr/0219-setup-plan-generated-archive-retention.md",
    "setup_health_generated_packet_archives_adr": "docs/adr/0220-setup-health-generated-packet-archives.md",
    "maintenance_generated_packet_archives_adr": "docs/adr/0221-maintenance-generated-packet-archives.md",
    "scheduler_plugin_blueprint": "docs/scheduler-plugin-blueprint.md",
    "scheduler_plugin_blueprint_scope": "plugin artifact shape, MCP setup tools, and hook boundaries",
    "scheduler_plugin_blueprint_adr": "docs/adr/0133-scheduler-plugin-blueprint.md",
    "mcp_schedule_plan_cron_entries_adr": "docs/adr/0134-mcp-schedule-plan-cron-entries.md",
    "cli_schedule_plan_adr": "docs/adr/0229-cli-schedule-plan.md",
    "setup_plan_cron_export_commands_adr": "docs/adr/0135-setup-plan-cron-export-commands.md",
    "maintenance_provider_readiness_adr": "docs/adr/0136-maintenance-provider-readiness.md",
    "maintenance_review_due_summary_adr": "docs/adr/0147-maintenance-review-due-summary.md",
    "provider_import_dry_run_adr": "docs/adr/0137-provider-import-dry-run.md",
    "provider_import_idempotency_adr": "docs/adr/0138-provider-import-idempotency.md",
    "mcp_git_lessons_adr": "docs/adr/0139-mcp-git-lessons.md",
    "git_lesson_idempotency_adr": "docs/adr/0140-git-lesson-idempotency.md",
    "hook_event_idempotency_adr": "docs/adr/0141-hook-event-idempotency.md",
    "scheduler_input_validation_adr": "docs/adr/0142-scheduler-input-validation.md",
    "hook_json_fingerprint_adr": "docs/adr/0143-hook-json-fingerprints.md",
    "hook_capture_review_report_adr": "docs/adr/0170-hook-capture-review-report.md",
    "weekly_maintenance_hook_capture_report_adr": "docs/adr/0171-weekly-maintenance-hook-capture-report.md",
    "weekly_maintenance_sleep_plan_report_adr": "docs/adr/0227-weekly-maintenance-sleep-plan-report.md",
    "schedule_plan_smoke_adr": "docs/adr/0230-schedule-plan-smoke.md",
    "hook_capture_review_outcomes_adr": "docs/adr/0172-hook-capture-review-outcomes.md",
    "mcp_hook_capture_review_adr": "docs/adr/0173-mcp-hook-capture-review.md",
    "hook_capture_review_filters_adr": "docs/adr/0174-hook-capture-review-filters.md",
    "hook_capture_archive_reviewed_adr": "docs/adr/0175-hook-capture-archive-reviewed.md",
    "hook_capture_date_window_filters_adr": "docs/adr/0176-hook-capture-date-window-filters.md",
    "mcp_schedule_validation_status_adr": "docs/adr/0144-mcp-schedule-validation-status.md",
    "scheduler_environment_diagnostic_adr": "docs/adr/0145-scheduler-environment-diagnostic.md",
    "false_positive_review_due_status_adr": "docs/adr/0146-false-positive-review-due-status.md",
    "false_positive_due_only_filter_adr": "docs/adr/0148-false-positive-due-only-filter.md",
    "stale_false_positive_suppression_audit_adr": "docs/adr/0149-stale-false-positive-suppression-audit.md",
    "maintenance_stale_suppression_summary_adr": "docs/adr/0150-maintenance-stale-suppression-summary.md",
    "scheduler_review_due_summary_adr": "docs/adr/0151-scheduler-review-due-summary.md",
    "maintenance_conflict_review_summary_adr": "docs/adr/0152-maintenance-conflict-review-summary.md",
    "maintenance_review_recommendation_summary_adr": "docs/adr/0195-maintenance-review-recommendation-summary.md",
    "setup_health_adr": "docs/adr/0153-setup-health-summary.md",
    "maintenance_profile_dry_run_adr": "docs/adr/0154-maintenance-profile-dry-run.md",
    "setup_health_maintenance_preflight_adr": "docs/adr/0155-setup-health-maintenance-preflight.md",
    "setup_health_validation_status_adr": "docs/adr/0179-setup-health-validation-status.md",
    "setup_health_recall_review_adr": "docs/adr/0180-setup-health-recall-review.md",
    "setup_health_context_config_adr": "docs/adr/0181-setup-health-context-config.md",
    "setup_health_manual_acceptance_adr": "docs/adr/0182-setup-health-manual-acceptance.md",
    "setup_health_vector_readiness_adr": "docs/adr/0183-setup-health-vector-readiness.md",
    "acceptance_template_adr": "docs/adr/0080-manual-acceptance-template.md",
    "false_positive_unignore_adr": "docs/adr/0081-mcp-false-positive-unignore.md",
    "review_configure_mode_adr": "docs/adr/0082-mcp-review-mode-configuration.md",
    "conflict_dismiss_receipt_adr": "docs/adr/0083-mcp-conflict-dismiss-receipts.md",
    "conflict_merge_receipt_adr": "docs/adr/0084-mcp-conflict-merge-proposal-receipts.md",
    "conflict_keep_reviewer_adr": "docs/adr/0085-mcp-conflict-keep-reviewer-receipts.md",
    "plugin_review_receipt_tools_adr": "docs/adr/0086-plugin-review-receipt-tools.md",
    "review_recommendation_artifacts_adr": "docs/adr/0188-review-recommendation-artifacts.md",
    "review_recommendation_status_adr": "docs/adr/0189-review-recommendation-status.md",
    "review_recommendation_outcome_links_adr": "docs/adr/0190-review-recommendation-outcome-links.md",
    "review_recommendation_outcome_status_adr": "docs/adr/0191-review-recommendation-outcome-status.md",
    "review_recommendation_outcome_report_adr": "docs/adr/0204-review-recommendation-outcome-report.md",
    "mcp_review_recommendation_outcome_report_adr": "docs/adr/0205-mcp-review-recommendation-outcome-report.md",
    "review_recommendation_outcome_report_pagination_adr": "docs/adr/0206-review-recommendation-outcome-report-pagination.md",
    "review_recommendation_archive_adr": "docs/adr/0196-review-recommendation-archive.md",
    "review_recommendation_outcome_report_cli": "python3 scripts/ai_dememory.py review recommendation-outcomes --json",
    "review_recommendation_outcome_report_pagination_cli": "python3 scripts/ai_dememory.py review recommendation-outcomes --limit",
    "review_recommendation_archive_cli": "python3 scripts/ai_dememory.py review recommendations-archive --json",
    "review_recommendation_archive_apply": "archive/review-recommendations/",
    "review_recommendation_archive_status_adr": "docs/adr/0197-review-recommendation-archive-status.md",
    "review_recommendation_archive_status_cli": "python3 scripts/ai_dememory.py review recommendations-archive-status",
    "review_recommendation_archive_restore_adr": "docs/adr/0198-review-recommendation-archive-restore.md",
    "review_recommendation_archive_restore_cli": "python3 scripts/ai_dememory.py review recommendations-archive-restore",
    "mcp_review_recommendation_archive_restore_preview_adr": "docs/adr/0199-mcp-review-recommendation-archive-restore-preview.md",
    "mcp_review_recommendation_archive_status_adr": "docs/adr/0200-mcp-review-recommendation-archive-status.md",
    "review_recommendation_recursive_archive_partitions_adr": "docs/adr/0201-review-recommendation-recursive-archive-partitions.md",
    "review_recommendation_archive_status_pagination_adr": "docs/adr/0202-review-recommendation-archive-status-pagination.md",
    "review_recommendation_archive_invalid_pagination_adr": "docs/adr/0203-review-recommendation-archive-invalid-pagination.md",
    "mcp_client_enabled_tools_smoke_adr": "docs/adr/0087-mcp-client-enabled-tools-smoke.md",
    "mcp_client_tools_list_pagination_smoke_adr": "docs/adr/0088-mcp-client-tools-list-pagination-smoke.md",
    "mcp_runtime_list_pagination_smoke_adr": "docs/adr/0089-mcp-runtime-list-pagination-smoke.md",
    "mcp_runtime_list_identity_smoke_adr": "docs/adr/0090-mcp-runtime-list-identity-smoke.md",
    "mcp_client_single_session_pagination_smoke_adr": "docs/adr/0091-mcp-client-single-session-pagination-smoke.md",
    "mcp_client_initialized_notification_smoke_adr": "docs/adr/0092-mcp-client-initialized-notification-smoke.md",
    "mcp_runtime_initialized_notification_smoke_adr": "docs/adr/0093-mcp-runtime-initialized-notification-smoke.md",
    "mcp_client_response_id_smoke_adr": "docs/adr/0094-mcp-client-response-id-smoke.md",
    "mcp_runtime_response_id_smoke_adr": "docs/adr/0095-mcp-runtime-response-id-smoke.md",
    "install_smoke_initialized_notification_adr": "docs/adr/0096-install-smoke-initialized-notification.md",
    "install_smoke_response_id_adr": "docs/adr/0097-install-smoke-response-id.md",
    "install_smoke_missing_response_adr": "docs/adr/0098-install-smoke-missing-response-diagnostics.md",
    "install_smoke_unexpected_response_adr": "docs/adr/0099-install-smoke-unexpected-response-id.md",
    "install_smoke_invalid_response_adr": "docs/adr/0100-install-smoke-invalid-response-id.md",
    "install_smoke_duplicate_response_adr": "docs/adr/0101-install-smoke-duplicate-response-id.md",
    "install_smoke_result_field_adr": "docs/adr/0102-install-smoke-result-field-diagnostics.md",
    "install_smoke_result_type_adr": "docs/adr/0103-install-smoke-result-type-diagnostics.md",
    "install_smoke_protocol_version_adr": "docs/adr/0104-install-smoke-protocol-version-diagnostics.md",
}


@dataclass(frozen=True)
class ChecklistGuardIssue:
    target: str
    message: str


def normalize(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def validate_release_checklist_text(text: str) -> list[ChecklistGuardIssue]:
    issues: list[ChecklistGuardIssue] = []
    normalized = normalize(text)
    for name, heading in REQUIRED_HEADINGS.items():
        if heading not in text:
            issues.append(ChecklistGuardIssue(f"release_checklist:{name}", f"missing heading: {heading}"))
    for name, snippet in REQUIRED_SNIPPETS.items():
        if normalize(snippet) not in normalized:
            issues.append(
                ChecklistGuardIssue(
                    f"release_checklist:{name}",
                    f"missing required checklist item: {snippet}",
                )
            )
    return issues


def validate_release_checklist(root: Path) -> list[ChecklistGuardIssue]:
    path = root / CHECKLIST_PATH
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return [ChecklistGuardIssue(str(CHECKLIST_PATH), "release checklist is missing")]
    return validate_release_checklist_text(text)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=None, help="Repository root. Defaults to this repo.")
    parser.add_argument("--json", action="store_true", help="Emit JSON output.")
    args = parser.parse_args(argv)

    root = repo_root(args.root)
    issues = validate_release_checklist(root)
    if args.json:
        print(json.dumps([asdict(issue) for issue in issues], indent=2))
    elif issues:
        print(f"Release checklist guard found {len(issues)} issue(s):", file=sys.stderr)
        for issue in issues:
            print(f"{issue.target}: {issue.message}", file=sys.stderr)
    else:
        print("Release checklist guard passed.")
    return 1 if issues else 0


if __name__ == "__main__":
    raise SystemExit(main())
